name: Build Docs

on: [push, pull_request]

jobs:
  docs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.7']
        julia-arch: [x64]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - name: Build docs
        run: |
          cd docs
          julia --color=yes --project=@. -e 'using Pkg; Pkg.instantiate();'
          julia --color=yes --project=@. make.jl